site_name: Han OS
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    scheme: default
    primary: grey
    accent: grey

extra_css:
  - stylesheets/extra.css

nav:
    - System Overview: index.md
    - Version Logs: v_log/index.md
    - Knowledge Base:
        - Readings:
            - Test 1: knowledge_base/readings/test1.md
        - Lab:
            - Godot development: knowledge_base/lab/godot_development.md
    - Life Observations:
        - Birding: 
            - 太平山: obs/birding/birding1.md
        - Cinema:
            - 《測試》: obs/cinema/movie1.md
        - Travel:
            - 旅行日誌測試: obs/travel/test1.md
    - Miscellaneous:
        - Snippets: misc/snippets.md
        - Inbox: misc/inbox.md

